ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM_SST1_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_345 = ', GC_345
      WRITE(*,2) 'GC_346 = ', GC_346
      WRITE(*,2) 'GC_348 = ', GC_348
      WRITE(*,2) 'GC_349 = ', GC_349
      WRITE(*,2) 'GC_462 = ', GC_462
